---
title: "Quick Start Guide"
output: html_document
---

**Please, follow these short steps to learn how to use this useful App**

## Step 1 out of 5
This RShiny app allows you to keep ordered your personal incomes and expenses, and lets you visualize some useful graphs.  

Supose that you have downloaded a .xlsx file from your bank website containing your incomes and expenses of the current year ([click here](https://github.com/jaimugarte/DTAR-Project-/raw/jaime_branch/datasets/example_bank_movements.xlsx) to download a simulated .xlsx file that we will use during the start guide. Please, take now 15 sec. to see the content of the file).   

## Step 2 out of 5
You can go now to **Data** in the top bar menu, click on the **Import** button located in the left side, and select the file already mentioned. You may see the content of the file in a table. Observe that each expense/income has been classified into some categories, thanks to two ingenious algorithms.


The Step 2 has this workflow:  
1) When *Import* button is clicked, the R Shiny connects with a google drive account (which stores the files of this App). If it is the first time the App is used, the imported file is stored with the name *data.xlsx*. If at the time of importing the file, the *data.xlsx* file already exists, then both files are combined (deleting repeated rows) and saved again in *data.xlsx*. The code of this part is available [here](https://github.com/jaimugarte/DTAR-Project-/).  
2) Then, the R Shiny structures the file with the appearance that is shown in the Shiny table, with the function *clean_data()*.
3) Then, the R Shiny uses two functions that classify the data:
  + *accurate_classification()*: classifies each row into classes directly when specific word(s) appears in the column *CONCEPTO* of the *data.xlsx* file.
  + *imprecise_classification()*: classifies each row based on a model that consider all columns of *data.xlsx* as possible predictor of the class. 

## Step 3 out of 5
Go now to **Control** in the top bar menu and examine the graphs that have been generated from the data.

## Step 4 out of 5
Return back to **Data** in the top bar menu. Choose the table *Categories*. In this table you can make double click to a class name and change it. In the columns *key1*,*key2*,... you can write words that when they appear in the *CONCEPT* field of a row in the *data.xlsx* they will classify that row with the corresponding class of that key word.

## Step 5 out of 5
Choose the table *Budget*. Edit the table by double click on each field. In the *Control* section you can check how real incomes/expenses coincide or not with this budget table.






